FriesI23/mhabit

- lib/common/consts.dart
- lib/provider/habit_detail.dart
- lib/provider/habit_summary.dart
- lib/view/for_habit_detail/habit_edit_repl_rcd_cal.dart
- lib/view/page_habits_display.dart
Add the action to open the skip reason dialog when a heatmap cell is long-pressed.
> feat: Add skip reason dialog on heatmap.

- assets/l10n/en.arb
- assets/l10n/zh.arb
- lib/component/widget.dart
- lib/component/widgets/theme_with_custom_colors.dart
- lib/db/db.dart
- lib/extension/num_extensions.dart
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/provider/habit_detail.dart
- lib/provider/habit_form.dart
- lib/view/app.dart
- lib/view/common/habit_record_number_picker.dart
- lib/view/common/habit_record_reason_modifier.dart
- lib/view/for_habit_detail/habit_edit_repl_rcd_cal.dart
- lib/view/for_habit_display/_dialog.dart
- lib/view/page_habit_detail.dart
- lib/view/page_habits_display.dart
- Add 'Maximum Daily Goal' value in Change Goal Dialog
- Add custom color on skipReason/changeGoal dialog
- Int like 1 shouldn't display decimal point
> Dialog optimization

- .github/workflows/release.yml
- fix artifact path with appbundle
- fix app signed progress
see [#15](https://github.com/FriesI23/mhabit/issues/15)
> fix(github-action): Fix github release action

- assets/l10n/en.arb
- assets/l10n/zh.arb
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/provider/habits_file_exporter.dart
- lib/view/common/_dialog.dart
- lib/view/common/exporter_confirm_dialog.dart
- lib/view/page_app_setting.dart
- lib/view/page_habit_detail.dart
- lib/view/page_habits_display.dart
- add confirm dialog when export
- add export records option
see: #23
> feat: export without habit records

- lib/view/for_habit_display/habit_display_main_menu.dart
see: #38
Thanks to "hashom" feedback on this bug.
> fix(filter): "Completed" and "Actived" filters have opposite effects

- lib/extension/num_extensions.dart
- lib/view/common/habit_record_number_picker.dart
Add  '-' and '+' buttons on the right side of the text field.
Thanks to @serrq suggestion
see also: #27
> Faster input method

- lib/component/widgets/habit_list_tile.dart
- lib/view/common/fixed_page_place_holder.dart
- lib/view/for_habit_display/habit_display_list_tile.dart
- lib/view/for_habit_display/habit_summary_list_tile.dart
- lib/view/page_habits_display.dart
reproduce this bug by adjusting android display size to max.
see: #46 on github
> fixed: FAB display overlap with habit

- assets/l10n/en.arb
- assets/l10n/zh.arb
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/view/page_habit_detail.dart
- add new text if habit not started.
see #52 on github
> fixed: summary text show negative number

- lib/view/for_habit_edit/habit_target_days_picker.dart
- add new optional
- refactor dialog
see #37 on github
> feat: Add new targetdays option

- assets/l10n/en.arb
- assets/l10n/zh.arb
- ios/Podfile.lock
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/model/habit_daily_goal.dart
- lib/model/habit_summary.dart
- lib/provider/habit_form.dart
- lib/view/common/habit_record_number_picker.dart
- lib/view/for_habit_edit/habit_edit_daily_goal_tile.dart
- lib/view/page_habit_edit.dart
- fixed positive habit's daily goal set to 0 problem in edit page
- fixed unable to switch habitType when editting exsit habit
see #64, #66 on github
> fix(view): issues caused by switch between normal/negative habits

- android/app/build.gradle
- android/app/src/main/res/values-fa/strings.xml
- assets/l10n/fa.arb
- lib/view/app.dart
This PR adds the Persian translation.
https://trello.com/c/uBUyqqbM/27-persian-support
> Initializing Persian Translation

- lib/component/widget.dart
- lib/component/widgets/markdown_body.dart
- lib/view/page_habit_detail.dart
> fix: incorrect markdown colors on memo string on dark mode

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/fa.arb
- assets/l10n/zh.arb
- configs/l10n.yaml
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/model/habit_stat.dart
- lib/model/habit_summary.dart
- lib/provider/habit_summary.dart
- fixed #82
- optimize translation
> fix: Ignored archived habit in most popular habit section

- lib/provider/habit_detail.dart
> fix: use the user-entered value for auto-complete

- lib/model/habit_display.dart
> fix: show completed habits even when archived

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/zh.arb
- docs/README/images/l10n-stat.svg
- lib/common/utils.dart
- lib/db/profile.dart
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/model/cache.dart
- lib/model/global.dart
- lib/model/habit_display.dart
- lib/view/for_app_setting/_dialog.dart
- lib/view/for_app_setting/app_setting_clear_cache.dart
- lib/view/for_habit_edit/habit_target_days_picker.dart
- lib/view/page_app_setting.dart
- lib/view/page_habit_edit.dart
- test/common_test/utils_test.dart
- add cache structure
- add target start days last filled cache
- add clear cache op
see #81 on github
> Feature/#81 Store the last filled number of target days

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/zh.arb
- configs/about_info.json
- lib/component/helper.dart
- lib/component/widgets/crypto_donate_button.dart
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/view/common/donate_dialog.dart
- lib/view/for_habit_detail/habit_detail_freq_chart.dart
- lib/view/page_app_about.dart
- provide a prompt after clicking buttons
- close dialog after clicking buttons
- adjust the button's transition effect.
- fix BNB Address
see #102 #112
> feat: optimize donate dialog

- lib/view/for_habit_detail/habit_edit_repl_rcd_cal.dart
- lib/view/for_habit_detail/habit_heatmap.dart
- pubspec.lock
- pubspec.yaml
- bump [simple_heatmap_calendar](https://github.com/FriesI23/simple_heatmap_calendar) to v0.2.0
linked issue: #109
> fix: month name alignment

- android/app/build.gradle
- android/app/src/main/res/values-de/strings.xml
- android/app/src/main/res/xml/locales_config.xml
- assets/l10n/de.arb
- docs/README/images/l10n-stat.svg
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_de.g.dart
- lib/view/app.dart
Hi,
I've translated the app into German. I did not generate l10n with `flutter`.
> Initialize German translation 🇩🇪

- android/app/build.gradle
- android/app/src/main/res/values-fr/strings.xml
- android/app/src/main/res/xml/locales_config.xml
- assets/l10n/fr.arb
- docs/add_new_locale_support.md
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_fr.g.dart
- lib/view/app.dart
Hello,
I want to contribute to mhabit with a French translation. If there is another French speaker here, it would be nice to check the result !
I also corrected a typo in the documentation ["Add new locale support"](https://github.com/FriesI23/mhabit/blob/main/docs/add_new_locale_support.md).
Best regards
> French translation

- assets/l10n/en.arb
- docs/README/images/l10n-stat.svg
- docs/add_new_locale_support.md
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_en.g.dart
- templates/git/commit-bugfix.template
- "defualt" in en.arb
- "asserts" in new locale wiki
resolved #136
> fix: typo issue in project

- lib/model/_score/calculator.dart
- lib/model/habit_score.dart
- lib/model/habit_summary.dart
- lib/provider/habit_summary.dart
- lib/view/page_habits_display.dart
- test/model_test/score_test.dart
- test/stub/habit_score.dart
- test/utils.dart
> [FEATURE] Freeze score if habit archived

- .vscode/settings.json
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- pubspec.lock
- add permissions required by flutter_local_notifications plugin
introduced this bug from commit 64938ffd
resolved #118, resolved #135
> fix(reminder): reminder broken on android platform

- lib/common/utils.dart
- lib/component/widgets/page_back_button.dart
- lib/view/page_habits_status_changer.dart
linked: https://github.com/flutter/flutter/issues/141497
> fix: opencontrainer raise exception when navigating via tooltips

- .github/actions/setup_jdk/action.yml
- .github/workflows/app-release.yml
- .vscode/settings.json
- docs/release.md
- add dmg action
- add pre-release switcher
- update java action version to v4
> chore: update release action

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/zh.arb
- docs/add_new_locale_support.md
- lib/common/consts.dart
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_ar.g.dart
- lib/l10n/localizations_de.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_fr.g.dart
- lib/l10n/localizations_it.g.dart
- lib/l10n/localizations_nb.g.dart
- lib/l10n/localizations_ru.g.dart
- lib/l10n/localizations_vi.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/persistent/profile/handler/app_language.dart
- lib/provider/app_language.dart
- lib/view/app.dart
- lib/view/for_app/app_providers.dart
- lib/view/for_app_setting/_dialog.dart
- lib/view/for_app_setting/app_language_changer.dart
- lib/view/page_app_setting.dart
Added a built-in language switching feature.
> In-App Language Switching

- assets/l10n/vi.arb
Translate-URL: https://hosted.weblate.org/projects/mhabit/app/vi/
Translation: Table Habit/app
> feat: update translation files

- android/app/build.gradle
- android/app/src/main/res/xml/locales_config.xml
- assets/l10n/zhtw.arb
- lib/common/consts.dart
I'm not sure if this is all set. Please let me know if there's anything else I should do :smile:
> Add a basic translation for zh-TW Traditional Chinese

- android/app/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- docs/faq.md
- ios/Podfile.lock
- lib/component/widgets/habit_freq_chart.dart
- lib/component/widgets/habit_score_chart.dart
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- upgrade gradle to 8.9
- upgrade com.android.application to 8.7.0
- upgrade androidx.window:window to 1.3.0
- upgrade androidx.window:window-java to 1.3.0
- upgrade com.android.tools:desugar_jdk_libs to 2.1.2
- change compatibile jave version from 1.8 to 17
- upgrade flutter package's major versions
- fl_chart to 0.69.0
- flutter_local_notifications to 17.2.3
- flutter_markdown to 0.7.3+2
- flutter_launcher_icons to 0.14.1
- bump flutter package versions, run 'git diff 62317cd 0ef4434 -- "pubspec.lock"' see full changelog
> feat: bump dependency versions

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/zh.arb
- lib/extension/navigator_extensions.dart
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_ar.g.dart
- lib/l10n/localizations_de.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_es.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_fr.g.dart
- lib/l10n/localizations_it.g.dart
- lib/l10n/localizations_nb.g.dart
- lib/l10n/localizations_pl.g.dart
- lib/l10n/localizations_pt.g.dart
- lib/l10n/localizations_ru.g.dart
- lib/l10n/localizations_tr.g.dart
- lib/l10n/localizations_uk.g.dart
- lib/l10n/localizations_vi.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/persistent/db_helper_builder.dart
- lib/persistent/db_helper_provider.dart
- lib/persistent/local/db_helper.dart
- lib/persistent/profile_builder.dart
- lib/persistent/profile_provider.dart
- lib/view/app.dart
- lib/view/common/xshare.dart
- lib/view/page_app_error.dart
- pubspec.lock
- pubspec.yaml
- Fix the incorrect implementation of some Completer instances in the code
- Add an error screen to be displayed.
---
> Fix Completer issues and add a startup error screen

- lib/view/for_habit_edit/habit_frequency_picker.dart
- lib/view/for_habit_edit/habit_target_days_picker.dart
> Fix: textfield text sinking on freq/targetday picker

- .github/workflows/_check.yml
- .github/workflows/app-release.yml
- .github/workflows/mr-check.yml
> chore: add code checking CI

- lib/model/habit_import.dart
- lib/persistent/local/db_helper.dart
- lib/persistent/local/handler/habit.dart
- lib/persistent/local/handler/record.dart
- lib/persistent/local/sql.dart
- lib/provider/habit_form.dart
- typo in var name of custom sql
- use correct type of field: Record.reason
- use "update" instead of "replace" when trying to insert multi records
> Fix: several issues from db helper

- lib/persistent/local/handler/habit.dart
- lib/persistent/local/handler/record.dart
- lib/provider/habit_status_changer.dart
> fix: use transaction when inserting multi record

- build.yaml
- lib/annotation/proxy_annotation.dart
- lib/builders/proxy_generator.dart
- lib/common/consts.dart
- lib/component/widgets/date_picker.dart
- lib/model/material_localizations.dart
- lib/model/material_localizations.g.dart
- lib/view/app.dart
- lib/view/for_habit_edit/habit_date_picker.dart
- pubspec.lock
- pubspec.yaml
> fix: ensure firstday config applied to calendar picker

- lib/provider/habit_detail.dart
- lib/provider/habit_status_changer.dart
- lib/provider/habit_summary.dart
> Fix: loadData complete twice when page initializes

- assets/l10n/_untranslated.json
- assets/l10n/en.arb
- assets/l10n/zh.arb
- lib/l10n/localizations.g.dart
- lib/l10n/localizations_ar.g.dart
- lib/l10n/localizations_cs.g.dart
- lib/l10n/localizations_de.g.dart
- lib/l10n/localizations_en.g.dart
- lib/l10n/localizations_es.g.dart
- lib/l10n/localizations_fa.g.dart
- lib/l10n/localizations_fr.g.dart
- lib/l10n/localizations_it.g.dart
- lib/l10n/localizations_nb.g.dart
- lib/l10n/localizations_pl.g.dart
- lib/l10n/localizations_pt.g.dart
- lib/l10n/localizations_ru.g.dart
- lib/l10n/localizations_tr.g.dart
- lib/l10n/localizations_uk.g.dart
- lib/l10n/localizations_vi.g.dart
- lib/l10n/localizations_zh.g.dart
- lib/view/page_habits_display.dart
> Fix snackbar text after deleting a habit

- .github/workflows/app-release.yml
- installers/macos_exporter/GithubExportOptions.plist
- Add code signing to GitHub Actions macOS build.
- Fix macOS app build failure error.
> chore: add code sign for macos app

- lib/provider/habits_file_exporter.dart
- lib/view/page_app_setting.dart
> Fix: Compatibility with habit import/export feature

- lib/component/helper.dart
- lib/provider/app_sync.dart
- lib/provider/habit_summary.dart
- lib/utils/async_debouncer.dart
- lib/view/common/_widget.dart
- lib/view/common/sync_now_tile.dart
- lib/view/for_habit_detail/habit_edit_repl_rcd_cal.dart
- lib/view/page_habit_detail.dart
- lib/view/page_habit_edit.dart
- lib/view/page_habits_display.dart
- lib/view/page_habits_status_changer.dart
- test/utils_test/async_debouncer_test.dart
~~- [ ] Show snackbar on sync failure~~ -- Split into separate PR
> Enhance WebDAV sync: trigger in some scenarios when auto-sync is enabled

- assets/l10n/uk.arb
- configs/contributors.json
- lib/l10n/localizations_uk.g.dart
Update Ukrainian l10n translation, thank for Preck757's contribution on Github.
> Update uk.arb (#281)

- lib/component/widgets/habit_progress_indicator.dart
- lib/model/habit_summary.dart
- lib/provider/habit_detail.dart
- lib/provider/habit_summary.dart
- lib/view/common/habit_summary_list_tile.dart
- lib/view/for_habit_detail/habit_detail_summary_tile.dart
- lib/view/for_habits_display/habit_display_list_tile.dart
- lib/view/page_habit_detail.dart
> fix: show UI feedback on habit deletion

- assets/l10n/_untranslated.json
- assets/l10n/ru.arb
- lib/l10n/localizations_ru.g.dart
- Update Russian translation, thanks to Yurt Page's contribution on Weblate.
> Weblate translation

- lib/view/common/habit_record_number_picker.dart
- lib/view/common/habit_record_reason_modifier.dart
- lib/view/for_habit_edit/habit_edit_app_bar.dart
- lib/view/for_habit_edit/habit_edit_daily_goal_extra_tile.dart
- lib/view/for_habit_edit/habit_edit_daily_goal_tile.dart
- lib/view/for_habit_edit/habit_edit_daily_goal_unit_tile.dart
- lib/view/for_habit_edit/habit_edit_desc_tile.dart
- lib/view/for_habit_edit/habit_reminder_tiles.dart
> Fix: improve hint visibility under low brightness

- lib/model/custom_date_format.dart
- lib/model/custom_date_format.g.dart
- lib/view/common/custom_datetime_format_picker.dart
> Feat: Add leading zero in date option

- android/settings.gradle
> fix: downgrade AGP to 8.11.1 due to fdroid incompatibility with >=8.12
